name: CI/CD Pipeline for MLOps Project

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}           # set this in repo Settings → Secrets
      DATASET_REPO: dhani10/tourism-app-dataset   # change if needed
      MODEL_REPO:   dhani10/tourism-model         # change if needed
      SPACE_ID:     dhani10/tourism-app           # change if needed
      MODEL_FILE:   model/best_model.joblib

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-

      - name: Install dependencies
        run: |
          python -V
          pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install pandas numpy scikit-learn datasets huggingface_hub joblib streamlit
          fi
          pip list

      # ---------- DATA PREPARATION ----------
      - name: Run Data Preparation
        run: python scripts/data_prep.py
        env:
          HF_TOKEN: ${{ env.HF_TOKEN }}
          DATASET_REPO: ${{ env.DATASET_REPO }}

      # ---------- TRAIN + REGISTER MODEL ----------
      - name: Run Model Training and Registration
        run: python scripts/train_and_register.py
        env:
          HF_TOKEN: ${{ env.HF_TOKEN }}
          DATASET_REPO: ${{ env.DATASET_REPO }}
          MODEL_REPO:   ${{ env.MODEL_REPO }}

      # ---------- DEPLOY TO HF SPACES ----------
      - name: Deploy to Hugging Face Spaces
        if: ${{ env.HF_TOKEN != '' }}
        run: python scripts/deploy_to_hf_space.py
        env:
          HF_TOKEN:   ${{ env.HF_TOKEN }}
          SPACE_ID:   ${{ env.SPACE_ID }}
          MODEL_REPO: ${{ env.MODEL_REPO }}
          MODEL_FILE: ${{ env.MODEL_FILE }}
          # Optional: set UPLOAD_DIR if your Space files live in a subfolder, e.g. "space"
          # UPLOAD_DIR: space
