# .github/workflows/mlops_pipeline.yml
name: CI/CD Pipeline for MLOps Project

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Data Preparation
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python scripts/data_prep.py

      - name: Run Model Training and Registration
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python scripts/train_and_register.py

      - name: Deploy to Hugging Face Spaces
        env:                         # <-- exposes the secret to the step
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          SPACE_ID: dhani10/tourism-app
          MODEL_REPOID: dhani10/tourism-model
        run: |
          python deploy_to_hf_space.py
